version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3001
    ports:
      - "8080:80"
    depends_on:
      - backend
